FROM alpine:3.20.0@sha256:77726ef6b57ddf65bb551896826ec38bc3e53f75cdde31354fbffb4f25238ebd


# TODO: install:
# - k9s
# - kubectl
# - helm
# - ct
# - go-yq
# - yamale
# - yamllint
RUN curl -sS https://webi.sh/k9s | sh
