name: Update

on:
  workflow_dispatch:
  schedule:
      # Run every day at midnight
    - cron: '0 0 * * *'

jobs:
  update:
    name: Update
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    strategy:
      matrix:
        containers:
          - app: nextcloud-fpm
          - app: nextcloud-notify_push
          - app: nextcloud-imaginary
    steps:
    - name: Checkout code
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

    - name: Run script
      run: |
        echo "Running update script for ${{ matrix.containers.app }}"
        script="apps/${{ matrix.containers.app }}/update.sh"
        if [ -f "$script" ]; then
          "$script" ./apps/${{ matrix.containers.app }}
        fi

    - uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4
      with:
        commit_message: Update ${{ matrix.containers.app }}
